config/routes.rb
Rails.application.routes.draw do

	devise_for :end_users, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations'
      }

  devise_for :admin, controllers:{
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
  }


  scope module: :public do
   get 'end_users/mypage' => 'end_users#show'
   get 'end_users/mypage/edit' => 'end_users#edit'
   patch 'end_users/mypage' => 'end_users#update'
   get 'end_users/confirm' => 'end_users#confirm'
   put "/end_users/confirm" => "end_users#withdraw"
   resources :items,only:[:index,:show]
   delete "/cart_items/destroy_all" => 'cart_items#destroy_all'
   resources :cart_items, only:[:index, :update, :destroy,:create]
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :orders, only:[:new, :create, :index, :show]
   resources :addresses, only:[:index, :edit, :create, :update, :destroy]
   resources :genres, only:[:show]


  end

  namespace :admin do
    resources :end_users
    get '/top' => 'top#top'
    resources :genres, only:[:new,:index,:create,:edit,:update]
    resources :items
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end

  root to: 'public/items#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

attachment :item_image
belongs_to :genre
has_many :cart_items
has_many :order_details

def self.search(search)
	if search
		Item.where(['name LIKE ?', "%#{search}%"])
	else
		Item.all
	end
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def index
	@items = Item.search(params[:search])
end

def new
	@item = Item.new
end

def create
	item = Item.new(item_params)
	item.save
	redirect_to admin_item_path(item.id)
end

def show
end

def edit
end

def update
end

private

def item_params
	params.require(:item).permit(:genre_id,:name,:text,:is_valid,:tax_free_price,:item_image)
end

end

app/views/admin/items/edit.html.erb
<div class="container">

<h3>商品編集</h3>


</div>

app/views/admin/items/index.html.erb
<div class="container">

<h3>商品一覧</h3>

<%=link_to "商品追加", new_admin_item_path,class:"btn btn-success" %>

<table class="table">
	<tr>
		<th>商品ID</th>
		<th>商品名</th>
		<th>税抜価格</th>
		<th>ジャンル</th>
		<th>ステータス</th>
	</tr>

	<% @items.each do |item| %>
	<tr>
		<td><%=item.id %></td>
		<td><%=item.name %></td>
		<td><%=item.tax_free_price %></td>
		<td><%=item.genre.name %></td>
		<td>
			<% if item.is_valid %>
			<p>販売中</p>
			<% else %>
			<p>販売停止中</p>
			<% end %>
		</td>
	</tr>
	<% end %>
</table>

</div>

app/views/admin/items/new.html.erb
<div class="container">

<h3>商品新規登録</h3>

<%= form_for(@item,url:'/admin/items') do |f| %>

<%=f.attachment_field :item_image %>

<label>商品名</label>
<%=f.text_field :name %>

<label>商品説明</label>
<%=f.text_area :text %>

<label>ジャンル</label>
<%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください" %>

<label>値段</label>
<%=f.text_field :tax_free_price %>

<label>販売ステータス</label>
<%=f.select :is_valid, [["販売中",true],["販売停止中",false]], include_blank: "選択してください" %>


<%=f.submit('新規登録',class:"btn btn-primary") %>






<% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container">

<h3>商品詳細</h3>

</div>