config/routes.rb
Rails.application.routes.draw do

	devise_for :end_users, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations'
      }

  devise_for :admin, controllers:{
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
  }


  scope module: :public do
   get 'end_users/mypage' => 'end_users#show'
   get 'end_users/mypage/edit' => 'end_users#edit'
   patch 'end_users/mypage' => 'end_users#update'
   get 'end_users/confirm' => 'end_users#confirm'
   put "/end_users/confirm" => "end_users#withdraw"
   resources :items,only:[:index,:show]
   delete "/cart_items/destroy_all" => 'cart_items#destroy_all'
   resources :cart_items, only:[:index, :update, :destroy,:create]
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :orders, only:[:new, :create, :index, :show]
   resources :addresses, only:[:index, :edit, :create, :update, :destroy]
   resources :genres, only:[:show]


  end

  namespace :admin do
    resources :end_users
    get '/top' => 'top#top'
    resources :genres, only:[:new,:index,:create,:edit,:update]
    resources :items
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end

  root to: 'public/items#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

	enum order_status:{pay_waiting: 0,pay_confirm: 1,on_making: 2,send_preparation: 3, sent:4}
	enum payment_method:{credit: 0,bunking: 1}

	belongs_to :end_user
	has_many :order_details

	validates :post_code, presence:true
	validates :address, presence:true
	validates :destination, presence:true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def index
	@orders = Order.all
end

def show
	@order = Order.find(params[:id])
end

def update
	@order = Order.find(params[:id])
	@order.update(order_params)
	#binding.pry
	if
		@order.order_status == "pay_confirm"
		@order.order_details.each do |order_detail|
			order_detail.update(making_status:1)
		end

	end


	redirect_back(fallback_location: admin_orders_path)
end

private
def order_params
	params.require(:order).permit(:order_status)
end


end

app/views/admin/orders/index.html.erb
<div class="container">

<table class="table">
	<tr>
		<th>購入日時</th>
		<th>購入者</th>
		<th>注文個数</th>
		<th>注文ステータス</th>
	</tr>

<% @orders.each do |order| %>

	<tr>
		<td>
			<%= link_to admin_order_path(order.id) do %>
			<%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
			<% end %>
		</td>
		<td>
			<%= order.end_user.last_name %><%= order.end_user.first_name %>
		</td>
		    <% @sum = 0 %>
		<td>
			<% order.order_details.each do |order_detail| %>

			  <% @sum += order_detail.amount %>
			<% end %>
			<%= @sum %>
		</td>
		<td><%= order.order_status_i18n %>
		</td>
	</tr>

<% end %>

</table>





</div>

app/views/admin/orders/show.html.erb
<div class="container">

<h3>注文履歴詳細</h3>

<div>
<label>購入者</label>
<%= @order.end_user.last_name %><%= @order.end_user.first_name %>
</div>

<div>
<label>配送先</label>
<%= @order.post_code %>
<%= @order.address %>
<%= @order.destination %>
</div>

<div>
<label>支払方法</label>
<%= @order.payment_method_i18n %>
</div>

<div>
<label>注文ステータス</label>
<%= form_for(@order, url:admin_order_path(@order.id)) do |f| %>
<%= f.select :order_status, Order.order_statuses.keys.map{|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
<%= f.submit "更新" %>
<% end %>

</div>

<div class="col-xs-8">
<table class="table">
	<tr>
		<th>商品名</th>
		<th>単価（税込）</th>
		<th>数量</th>
		<th>小計</th>
		<th>制作ステータス</th>
		<th></th>
	</tr>

<% @sum = 0 %>
<% @order.order_details.each do |order_detail| %>
	<tr>
		<td><%= order_detail.item.name %></td>
		<td><%= (order_detail.item.tax_free_price * 1.1).round %></td>
		<td><%= order_detail.amount %></td>
		<td><%= ((order_detail.item.tax_free_price * 1.1) * order_detail.amount).round %></td>
		<td>
			<%= form_for(order_detail, url:admin_order_detail_path(order_detail.id)) do |f| %>
			<%= f.select :making_status, OrderDetail.making_statuses.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>

			<%= f.submit "更新" %>
			<% end %>
		</td>
		<td></td>
	</tr>

	<% @sum += ((order_detail.item.tax_free_price * 1.1) * order_detail.amount).round %>
	<% end %>
</table>
</div>

<div class="col-xs-4">
<table class="table">
	<tr>
		<th>商品合計</th>
		<td><%= @sum %>円</td>
	</tr>

	<tr>
		<th>送料</th>
		<td>800円</td>
	</tr>

	<tr>
		<th>請求金額合計</th>
		<td><%= @sum + 800 %>円</td>
	</tr>
</table>
</div>


</div>