config/routes.rb
Rails.application.routes.draw do

	devise_for :end_users, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations'
      }

  devise_for :admin, controllers:{
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
  }


  scope module: :public do
   get 'end_users/mypage' => 'end_users#show'
   get 'end_users/mypage/edit' => 'end_users#edit'
   patch 'end_users/mypage' => 'end_users#update'
   get 'end_users/confirm' => 'end_users#confirm'
   put "/end_users/confirm" => "end_users#withdraw"
   resources :items,only:[:index,:show]
   delete "/cart_items/destroy_all" => 'cart_items#destroy_all'
   resources :cart_items, only:[:index, :update, :destroy,:create]
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :orders, only:[:new, :create, :index, :show]
   resources :addresses, only:[:index, :edit, :create, :update, :destroy]
   resources :genres, only:[:show]


  end

  namespace :admin do
    resources :end_users
    get '/top' => 'top#top'
    resources :genres, only:[:new,:index,:create,:edit,:update]
    resources :items
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end

  root to: 'public/items#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
	@genre = Genre.new
	@genres = Genre.all
end

def create
	genre = Genre.new(genre_params)
	genre.save
	redirect_to admin_genres_path
end

def edit
	@genre = Genre.find(params[:id])
end

def update
	genre = Genre.find(params[:id])
	genre.update(genre_params)
	redirect_to admin_genres_path
end

private
def genre_params
	params.require(:genre).permit(:name,:is_valid)
end

end

app/views/admin/genres/edit.html.erb
<div class="container">
<div class="row">

<h3>ジャンル編集</h3>

<%=form_for(@genre, url:"/admin/genres/#{@genre.id}") do |f| %>

<label>ジャンル</label>
<%=f.text_field :name %>

<label><%=f.radio_button :is_valid, true %>有効</label>
<label><%=f.radio_button :is_valid, false %>無効</label>

<%=f.submit('変更を保存する',class:"btn btn-primary") %>

<% end %>

</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
<div class="row">

<h3>ジャンル一覧・追加</h3>

<%=form_for(@genre, url:'/admin/genres') do |f| %>

<label>ジャンル</label>
<%=f.text_field :name %>

<label><%=f.radio_button :is_valid, "true" %>有効</label>
<label><%=f.radio_button :is_valid, "false" %>無効</label>

<%=f.submit('追加', class:"btn btn-primary") %>

<% end %>

<table class="table">
	<tr>
		<th>ジャンル</th>
		<th>状態</th>
		<th></th>
	</tr>

	<% @genres.each do |genre| %>
	<tr>
		<td><%=genre.name%></td>
		<td><% if genre.is_valid %>
			<p>有効</p>
			<% else %>
			<p>無効</p>
			<% end %>
		</td>
		<td>
			<%=link_to "編集", edit_admin_genre_path(genre.id) %>
		</td>
	</tr>
	<% end %>

</table>

</div>
</div>