config/routes.rb
Rails.application.routes.draw do

	devise_for :end_users, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations'
      }

  devise_for :admin, controllers:{
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
  }


  scope module: :public do
   get 'end_users/mypage' => 'end_users#show'
   get 'end_users/mypage/edit' => 'end_users#edit'
   patch 'end_users/mypage' => 'end_users#update'
   get 'end_users/confirm' => 'end_users#confirm'
   put "/end_users/confirm" => "end_users#withdraw"
   resources :items,only:[:index,:show]
   delete "/cart_items/destroy_all" => 'cart_items#destroy_all'
   resources :cart_items, only:[:index, :update, :destroy,:create]
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :orders, only:[:new, :create, :index, :show]
   resources :addresses, only:[:index, :edit, :create, :update, :destroy]
   resources :genres, only:[:show]


  end

  namespace :admin do
    resources :end_users
    get '/top' => 'top#top'
    resources :genres, only:[:new,:index,:create,:edit,:update]
    resources :items
    resources :orders, only:[:index,:show,:update]
    resources :order_details, only:[:update]
  end

  root to: 'public/items#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

	belongs_to :end_user

    validates :post_code, presence:true
	validates :address, presence:true
	validates :destination, presence:true


def total_address
	post_code + address + destination
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :end_user
	belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :post_code, presence:true
  validates :address, presence:true
  validates :phone_number, presence:true

  has_many :cart_items
  has_many :addresses
  has_many :orders


   def active_for_authentication?
   	super && (self.is_valid == true )
   	#superはdeviseの元々の認証機能を継承してる
   	#かつ、退会していないか。つまり、これで退会しているユーザを省く！
   end
end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

attachment :item_image
belongs_to :genre
has_many :cart_items
has_many :order_details

def self.search(search)
	if search
		Item.where(['name LIKE ?', "%#{search}%"])
	else
		Item.all
	end
end

end

app/models/order.rb
class Order < ApplicationRecord

	enum order_status:{pay_waiting: 0,pay_confirm: 1,on_making: 2,send_preparation: 3, sent:4}
	enum payment_method:{credit: 0,bunking: 1}

	belongs_to :end_user
	has_many :order_details

	validates :post_code, presence:true
	validates :address, presence:true
	validates :destination, presence:true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :item
	belongs_to :order

	enum making_status:{unable_to_commit: 0,waiting_making: 1,making: 2,made: 3}
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController

def index
	@end_users = EndUser.all
end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
	@genre = Genre.new
	@genres = Genre.all
end

def create
	genre = Genre.new(genre_params)
	genre.save
	redirect_to admin_genres_path
end

def edit
	@genre = Genre.find(params[:id])
end

def update
	genre = Genre.find(params[:id])
	genre.update(genre_params)
	redirect_to admin_genres_path
end

private
def genre_params
	params.require(:genre).permit(:name,:is_valid)
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def index
	@items = Item.search(params[:search])
end

def new
	@item = Item.new
end

def create
	item = Item.new(item_params)
	item.save
	redirect_to admin_item_path(item.id)
end

def show
end

def edit
end

def update
end

private

def item_params
	params.require(:item).permit(:genre_id,:name,:text,:is_valid,:tax_free_price,:item_image)
end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def index
	@orders = Order.all
end

def show
	@order = Order.find(params[:id])
end

def update
	@order = Order.find(params[:id])
	@order.update(order_params)
	#binding.pry
	if
		@order.order_status == "pay_confirm"
		@order.order_details.each do |order_detail|
			order_detail.update(making_status:1)
		end

	end


	redirect_back(fallback_location: admin_orders_path)
end

private
def order_params
	params.require(:order).permit(:order_status)
end


end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < ApplicationController

def top
end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?



protected

def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :kana_last_name, :kana_first_name, :post_code, :address, :phone_number])
end

def after_sign_in_path_for(resource)
	case resource
    when EndUser
         end_users_mypage_path
    when Admin
	     admin_top_path
    end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header class="navbar">
    <div class="container">

<nav>

    <% if end_user_signed_in? %>

    <nav class="nav navbar-nav navbar-left">

    <li><%= link_to '(*^^*)Nagano Cake(*^^*)', root_path %></li>

    </nav>

    <ul class="nav navbar-nav navbar-right">

    <li><%=link_to 'マイページ',end_users_mypage_path %></li>
    <li><%=link_to "商品一覧", items_path %></li>
    <li><%=link_to "カート",cart_items_path %></li>
    <li><%= link_to 'ログアウト',destroy_end_user_session_path, method: :delete %></li>

    </ul>

   <% elsif admin_signed_in? %>

    <nav class="nav navbar-nav navbar-left">
    <li><%= link_to 'NaganoCake', new_admin_session_path %></li>
    </nav>

    <ul class="nav navbar-nav navbar-right">

    <li><%=link_to "商品一覧",admin_items_path %></li>
    <li><%=link_to "会員一覧",admin_end_users_path %></li>
    <li><%=link_to "注文履歴一覧", admin_orders_path %></li>
    <li><%=link_to "ジャンル一覧", admin_genres_path %></li>
    <li><%=link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>

    </ul>

    <div class="col-xs-offset-9 col-xs-3">
    <%= form_tag(admin_items_path,:method => 'get') do %>
        <%= text_field_tag :search %>
        <%= submit_tag 'Search', :name => nil %>
    <% end %>
    </div>

    <% else %>

    <nav class="nav navbar-nav navbar-left">

    <li><%= link_to 'NaganoCake!', root_path %></li>

    </nav>

    <ul class="nav navbar-nav navbar-right">

    <li><%=link_to "商品一覧", items_path %></li>
    <li><%= link_to '新規登録', new_end_user_registration_path %></li>
    <li><%= link_to 'ログイン', new_end_user_session_path %></li>

    <% end %>
</ul>
</nav>
</div>
</header>
    <%= yield %>
  </body>
</html>